<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class  Post extends Model
{
    use HasFactory;
    public function getRouteKeyName(){
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function createdBy(){
        return $this->belongsTo(User::class, 'created_by', 'id');
    }
    public function updatedBy(){
        return $this->belongsTo(User::class, 'updated_by', 'id');
    }
    public function categories(){
        return $this->belongsToMany(Category::class,  'post_categories');
    }
    public function tags(){
        return $this->belongsToMany(Tag::class,  'post_tags');
    }
    public function replies(){
        return $this->hasMany(Reply::class);
    }
    public function postView(){
        return $this->hasMany(PostView::class);
    }
    public function showPost(){
        if(auth()->id()==null){
            return $this->postView()
                ->where('ip', '=',  request()->ip())->exists();
        }

        return $this->postView()
            ->where(function($postViewsQuery) { $postViewsQuery
                ->where('session_id', '=', request()->getSession()->getId())
                ->orWhere('user_id', '=', (auth()->check()));})->exists();
    }
}
